export { GeneralSection } from "./GeneralSection";
export { ListenSection } from "./ListenSection";
export { DisplaySection } from "./DisplaySection";
export { DictSection } from "./DictSection";
export { TranslateSection } from "./TranslateSection";
export { ImageCaptureSection } from "./ImageCaptureSection";
export { AgentSection } from "./AgentSection";
export { AdvancedConfigSection } from "./AdvancedConfigSection";
export { TtsSection } from "./TtsSection";
